hydra:
  run:
    dir: outputs/${data.dataname}/${model.modelname}/${model.ckpt.name}/${experiment}/${run_name}
  job: # automatically go to the job folder (needed for hydra > 1.2 with new behavior)
    chdir: true

# Global configurations shared between different modules
experiment: tv-${model.model.train_vit}_loss-${model.model.loss.name}_lr-${model.optimizer.lr}
run_name: base

seed: 1234
logger_level: INFO

# Composing nested config with default
defaults:
  - _self_
  - data: webvid-covr
  - machine: server
  - trainer: gpu
  - test: all
  - trainer/logger: csv
  - model: blip-large
  - model/optimizer: adamw
  - model/scheduler: cosine
  - model/loss: hn_nce
  - model/ckpt: blip-l-coco

  - experiment: null

paths: ${machine.paths}

# Flag to validate at the end of every epoch
val: True
